version: '2'

services:
  api:
    build:
      context: ./api
    #image: bgauduch/iotgateway-api
    ports:
      - 8080:8080
    links: 
      - influxdb
  influxdb:
    image: tutum/influxdb
    ports: # should use "expose" for production
      - 8083:8083
      - 8086:8086
